### ISSUE TITLE
Wrong condo env name in bootstrap.sh

### ISSUE THREAD

**Issue by khaferkamp** [al-mz/ecommerce-analytical-dashboard#21]
Hi Ali,

thanks for your work! Enjoying it!

I found the mistake in the boostrap.sh.
The conda env name is 'eco' :)

I could not create a PR (just in my fork) but thought this might help for others as well to enjoy your work!!

Best Regards
Kevin

**Comment by ali-mhmzadeh** [comment]
Hi Kevin, 

Thanks for the feedback :)

Yes, you're right. The conda env name was mistakenly set in boostrap.sh file, and it should now be fixed after merging the PR.
