### ISSUE TITLE
i am getting SECRET_KEY error

### ISSUE THREAD

**Issue by Jaykin001** [al-mz/ecommerce-analytical-dashboard#23]
superset    | --------------------------------------------------------------------------------
superset    |                                     WARNING
superset    | --------------------------------------------------------------------------------
superset    | A Default SECRET_KEY was detected, please use superset_config.py to override it.
superset    | Use a strong complex alphanumeric string and use a tool to help you generate 
superset    | a sufficiently random sequence, ex: openssl rand -base64 42
superset    | --------------------------------------------------------------------------------
superset    | --------------------------------------------------------------------------------

**Comment by al-mz** [comment]
Hi, 

The issue with the SECRET_KEY warning has been resolved in the latest updates. You can now override the default SECRET_KEY by configuring it in ./.envs/.superset.env file.
